<?php

namespace ShopBundle\Repository;

/**
 * productUsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductUsersRepository extends \Doctrine\ORM\EntityRepository
{
}

