<?php

namespace ShopBundle\Repository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\ClassMetadata;
use ShopBundle\Entity\ProductCategory;

/**
 * ProductCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductCategoryRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * @var EntityManagerInterface $em
	 */
	private $em;

	/**
	 * PromotionRepository constructor.
	 *
	 * @param EntityManagerInterface $em
	 * @param ClassMetadata $class
	 */
	public function __construct( EntityManagerInterface $em ,ClassMetadata $class = null) {
		parent::__construct( $em,new ClassMetadata(ProductCategory::class));
		$this->em = $em;
	}

	public function findAllCategoriesTree(){
		$query = $this->em->createQuery('SELECT c 
											  FROM ShopBundle\Entity\ProductCategory c
											  WHERE c.parent IS NULL');
		return $query->getResult();
	}

	public function getSubcategoryIds($id){
		$query = $this->em->createQuery('SELECT c.id
											  FROM ShopBundle\Entity\ProductCategory c
											  WHERE c.parent = :id	'
		)->setParameter('id',$id)
		;
		return $query->getResult();
	}

}
