<?php

namespace ShopBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllWithJoin(){
        $query = $this->getEntityManager()
            ->createQuery('SELECT p , pr, c FROM ShopBundle:Product p
                          JOIN p.promotion pr 
                          JOIN p.category c
                           ')
            ->getResult();
        return $query;
    }

    public function findOneWithJoin($id){
        $query = $this->getEntityManager()
            ->createQuery('SELECT p , pr, c FROM ShopBundle:Product p
                          JOIN p.promotion pr 
                          JOIN p.category c
                          WHERE p.id = :id
                           ')
            ->setParameter(':id',$id);
        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
