<?php

namespace AppBundle\Repository;

/**
 * UserAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAddressRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAddressJoinUser($id){
		$em = $this->getEntityManager();
		$query = $em->createQuery("SELECT adr, u 
									  	FROM AppBundle:UserAddress adr 
									  	JOIN adr.user u 
									  	WHERE u.id = :id")
		;
		$query->setParameter('id',$id);
		try{
			return $query->getSingleResult();
		}   catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	}
}
