<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function findSuperAdminUser(){
		$em = $this->getEntityManager();
		$query = $em->createQuery("SELECT u FROM AppBundle:User u JOIN u.roles r WHERE r.name = 'ROLE_SUPER_ADMIN'");
		try{
			return $query->getSingleResult();
		}   catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	}

	public function findUserJoinAddress($id){
		$em = $this->getEntityManager();
		$query = $em->createQuery("SELECT u, adr 
									  	FROM AppBundle:User u 
									  	JOIN u.address adr 
									  	WHERE u.id = :id")
		;
		$query->setParameter('id',$id);
		try{
			return $query->getSingleResult();
		}   catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	}
}
