<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	/**
	 * @return mixed|null
	 * @throws \Doctrine\ORM\NonUniqueResultException
	 */
	public function findSuperAdminUser(){
		$em = $this->getEntityManager();
		$query = $em->createQuery("SELECT u 
										FROM AppBundle:User u 
										JOIN u.roles r 
										WHERE r.name = 'ROLE_SUPER_ADMIN'");
		try{
			return $query->getSingleResult();
		}   catch ( NoResultException $e) {
			return null;
		}
	}

	/**
	 * @param $id
	 *
	 * @return mixed|null
	 * @throws \Doctrine\ORM\NonUniqueResultException
	 */
	public function findUserJoinAddress($id){
		$em = $this->getEntityManager();
		$query = $em->createQuery("SELECT u, adr 
									  	FROM AppBundle:User u 
									  	JOIN u.address adr 
									  	WHERE u.id = :id")
		;
		$query->setParameter('id',$id);
		try{
			return $query->getSingleResult();
		} catch ( NoResultException $e) {
			return null;
		}
	}
}
