# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    role_hierarchy:
            ROLE_ADMIN:       [ROLE_EDITOR,ROLE_USER]
            ROLE_BLOG_ADMIN:  [ROLE_EDITOR,ROLE_USER]
            ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_BLOG_ADMIN]
    encoders:
        AppBundle\Entity\User:
           algorithm: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        db_provider:
              entity:
                  class: AppBundle\Entity\User
                  property: username

    firewalls:
        secured_area:
              pattern: ^/

              anonymous: true

              form_login:
                  login_path: login
                  check_path: login
                  csrf_token_generator: security.csrf.token_manager
                  default_target_path: home_page
                  always_use_default_target_path: true
                  remember_me: true
              logout:
                  # The route name the user can go to in order to logout
                  path: /logout
                  # The name of the route to redirect to after logging out
                  target: article_index

              remember_me:
                          secret:  '%secret%'
                          lifetime: 604800 # 1 week in seconds
                          path: /



    access_control:
