services:
      _defaults:
              # automatically injects dependencies in your services
              autowire: true
              # automatically registers your services as commands, event subscribers, etc.
              autoconfigure: true
              # this means you cannot fetch services directly from the container via $container->get()
              # if you need to do this, you can override this setting on individual services
              public: true
      ShopBundle\:
              resource: '../../*'
              # you can exclude directories or files
              # but if a service is unused, it's removed anyway
              exclude: '../../{Entity,Repository,Tests}'

          # controllers are imported separately to make sure they're public
          # and have a tag that allows actions to type-hint services
      ShopBundle\Controller\:
              resource: '../../Controller'
              public: true
              tags: ['controller.service_arguments']

      ShopBundle\Services\ProductService:
              arguments:
                          $targetDir: '%product_image_upload%'

      ShopBundle\Services\ProductServiceInterface:
              alias: 'ShopBundle\Services\ProductService'
              public: false

      ShopBundle\Services\ProductUsersInterface:
              alias: 'ShopBundle\Services\ProductUsersService'
              public: false

      ShopBundle\Services\PromotionServiceInterface:
              alias: 'ShopBundle\Services\PromotionService'
              public: false

      ShopBundle\Services\OrderServiceInterface:
              alias: 'ShopBundle\Services\OrderService'
              public: false

      ShopBundle\Services\ProductCategoryInterface:
              alias: 'ShopBundle\Services\ProductCategoryService'
              public: false